version: 1.0.{build}
image: Visual Studio 2017
nuget:
  project_feed: true
before_build:
- ps: Write-Host -Object "This CI is working by appveyor.yml..."
- cmd: nuget restore Dicom.Desktop.sln -source https://www.nuget.org/api/v2
build:
  project: DICOM.Desktop.sln
  verbosity: normal